name: Deploy

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write


jobs:
  merge_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Merge Validation
        run: echo "Merge Pull Request into Mai"

      - name: Delete Dev Branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          branches: dev

      - name: Recreate Dev Branch
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "CI Bot"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git checkout -b dev origin/main
          git push origin dev

