name: PROD

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  merge_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Git Config
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "CI Bot"

      - name: Merge Main into Test
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          
          git checkout dev
          git fetch origin dev
          git merge origin/dev

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          gh auth login --with-token <<< "${GH_TOKEN}"
          gh pr create --base main --head dev --title "Merge dev into main" --body "Automated PR from CI workflow"
