name: Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  merge_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Merge Validation
        run: echo "Merge Pull Request into Main"

      - name: Recreate Dev Branch
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "CI Bot"
          git checkout dev
          git reset --hard main
          git push origin dev --force