name: PROD

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  merge_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          branch: dev
          base: main
          title: "Automated PR - Feature vers Main"
          body: |
            Cette PR est créée automatiquement par GitHub Actions 🚀
          draft: false
          delete-branch: false
