name: TEST

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  update-from-origin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Git Config
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "CI Bot"

      - name: Merge Main into Test
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          
          git checkout test
          git fetch origin main
          git merge origin/main
          
          git push origin test
