name: Test branch

on:
  push:
    branches:
      - main

jobs:
  recreate_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Recreate Test Branch
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "CI Bot"
          git checkout -b test
          git push origin test --force
