name: Test branch

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  merge_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "ci@github.com"
      
      - name: Pull with rebase (automatic resolution of conflicts)
        run: |
          git fetch origin
          git rebase origin/test || (git rebase --abort && git merge --strategy=recursive --strategy-option=theirs origin/test)
      
      - name: Push changes
        run: git push origin test
