name: Test branch

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  merge_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fetch and Merge Changes
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "CI Bot"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git fetch origin test
          git merge --strategy-option theirs origin/test || git merge --allow-unrelated-histories origin/test
          git add .
          git rebase --continue || echo "No rebase needed"
          git push origin test --force

