name: Test branch

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write


jobs:
  update_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update Test Branch
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "CI Bot"
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}
          git fetch origin
          git checkout test || git checkout -b test
          git reset --hard origin/main
          git push origin test
