name: Main => Test

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  copy-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push Main to Test
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout test || git checkout -b test
          git merge origin/main --no-edit
          git push origin test
