name: Test branch

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  merge_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fetch and Merge Changes
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "CI Bot"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git checkout test
          git fetch origin
          git checkout main
          git pull origin main
          git checkout test
          git merge main


